# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('plan', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joining_users', models.ManyToManyField(related_name='joining_trips', to='belt.User')),
                ('planned_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_trips', to='belt.User')),
            ],
        ),
    ]
