# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_auto_20180202_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('plan', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joining_users', models.ManyToManyField(related_name='joining_travels', to='belt.User')),
                ('planned_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_travels', to='belt.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='joining_users',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='planned_by_user',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
